name: clean_core
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

   #icon
  ionicons: ^0.2.2
  #state management
  flutter_bloc: ^8.1.3
  #comparing dart objects
  equatable: ^2.0.5
  #service locator
  get_it: ^7.6.4
  #dateFormat
  intl: ^0.18.1
  #make request to api
  retrofit: ^4.0.3
  #Hooks
  flutter_hooks: ^0.20.3
  #chached image
  cached_network_image: ^3.3.0
  #internet
  internet_connection_checker: ^1.0.0+1
  #responsive
  responsive_framework: ^1.1.1
  #svg
  flutter_svg: ^2.0.9
  #share
  url_launcher: ^6.2.1
  #display mode
  flutter_displaymode: ^0.6.0
  #shimmer
  shimmer: ^3.0.0
  #flutter_animate
  flutter_animate: ^4.2.0+1
  #Database
  floor: any



dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0
  flutter_lints: ^3.0.1
  retrofit_generator: ^8.0.4
  floor_generator: ^1.4.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Gotham
      fonts:
        - asset: fonts/gotham_light.otf
          weight: 300
        - asset: fonts/gotham_book.otf
          weight: 400
        - asset: fonts/gotham_medium.otf
          weight: 500
        - asset: fonts/gotham_bold.otf
          weight: 700
        - asset: fonts/gotham_ultra.otf
          weight: 800
        - asset: fonts/gotham_black.otf
          weight: 900

