name: clean_core
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

#Dependencys
dependencies:
  flutter:
    sdk: flutter
  # Service Locator
  get_it: ^7.2.0
  # State Management
  provider: ^6.0.2
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  # Networking
  internet_connection_checker: ^0.0.1+3
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1
  network_logger: ^1.0.1
  #Utils
  url_launcher: ^6.0.20
  json_annotation: ^4.4.0
  #UI
  flutter_svg: ^1.0.3
  logger: ^1.1.0
  #IOS
  cupertino_icons: ^1.0.4

#Dev Dependency
dev_dependencies:
  flutter_test:
    sdk: flutter
  #Utils
  change_app_package_name: ^1.0.0
  json_serializable: ^6.1.6
  build_runner: ^2.1.10
  #lints
  flutter_lints: ^1.0.4
  lint: ^1.8.2
  #test
  http_mock_adapter: ^0.3.2
  bloc_test: ^9.0.3
  mockito: ^5.1.0
#Resources
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Gotham
      fonts:
        - asset: fonts/gotham_light.otf
          weight: 300
        - asset: fonts/gotham_book.otf
          weight: 400
        - asset: fonts/gotham_medium.otf
          weight: 500
        - asset: fonts/gotham_bold.otf
          weight: 700
        - asset: fonts/gotham_ultra.otf
          weight: 800
        - asset: fonts/gotham_black.otf
          weight: 900

